modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="cursed_forge"
version="1.2"
displayName="Cursed Forge"
displayURL="https://modrinth.com/mod/cursed-forge"
logoFile="logo.png"
credits="rovio, nintendo, and created by Titanskywars"
authors="Titanskywars"
description="normal mod lol"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.cursed_forge]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.137,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.cursed_forge]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration